// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEwJ58rVbkSuQhg1gWiIb_LBoxBAPEc5A',
    appId: '1:1006584668487:web:cb3be70d3a64644e252c62',
    messagingSenderId: '1006584668487',
    projectId: 'mechat-96',
    authDomain: 'mechat-96.firebaseapp.com',
    storageBucket: 'mechat-96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5UPuWu5d9URiMy-_TUdN3HgmO5PD7Lrc',
    appId: '1:1006584668487:android:431fa2892078529c252c62',
    messagingSenderId: '1006584668487',
    projectId: 'mechat-96',
    storageBucket: 'mechat-96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6dk_ayzocNE870BCHs8O1V_PIjVQEoA4',
    appId: '1:1006584668487:ios:4cfeb055557fff5f252c62',
    messagingSenderId: '1006584668487',
    projectId: 'mechat-96',
    storageBucket: 'mechat-96.firebasestorage.app',
    androidClientId: '1006584668487-7b7jbnhntituro83tn996e5rcls73h2h.apps.googleusercontent.com',
    iosClientId: '1006584668487-ogbj4bbh0kmct0adckg8qscskq614vbj.apps.googleusercontent.com',
    iosBundleId: 'com.mechat.mechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6dk_ayzocNE870BCHs8O1V_PIjVQEoA4',
    appId: '1:1006584668487:ios:4cfeb055557fff5f252c62',
    messagingSenderId: '1006584668487',
    projectId: 'mechat-96',
    storageBucket: 'mechat-96.firebasestorage.app',
    androidClientId: '1006584668487-7b7jbnhntituro83tn996e5rcls73h2h.apps.googleusercontent.com',
    iosClientId: '1006584668487-ogbj4bbh0kmct0adckg8qscskq614vbj.apps.googleusercontent.com',
    iosBundleId: 'com.mechat.mechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEwJ58rVbkSuQhg1gWiIb_LBoxBAPEc5A',
    appId: '1:1006584668487:web:ecf2298a771927d6252c62',
    messagingSenderId: '1006584668487',
    projectId: 'mechat-96',
    authDomain: 'mechat-96.firebaseapp.com',
    storageBucket: 'mechat-96.firebasestorage.app',
  );
}
