import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'advanced_theme_model.freezed.dart';
part 'advanced_theme_model.g.dart';

@freezed
abstract class AdvancedThemeModel with _$AdvancedThemeModel {
  const AdvancedThemeModel._();
  const factory AdvancedThemeModel({
    required String id,
    required String name,
    @Default('') String description,
    @Default('Modern') String category,
    required BubbleTheme senderBubble,
    required BubbleTheme receiverBubble,
    required ChatTextTheme textTheme,
    required ChatBackgroundTheme backgroundTheme,
    required AppAppearanceTheme appAppearance,
  }) = _AdvancedThemeModel;

  factory AdvancedThemeModel.fromJson(Map<String, dynamic> json) =>
      _$AdvancedThemeModelFromJson(json);

  static TextStyle safeGetFont(
    String fontFamily, {
    Color? color,
    double? fontSize,
    FontWeight? fontWeight,
  }) {
    try {
      return GoogleFonts.getFont(
        fontFamily,
        color: color,
        fontSize: fontSize,
        fontWeight: fontWeight,
      );
    } catch (_) {
      return TextStyle(
        fontFamily: fontFamily,
        color: color,
        fontSize: fontSize,
        fontWeight: fontWeight,
      );
    }
  }

  ThemeData toThemeData([Brightness? requestedBrightness]) {
    final Brightness defaultBrightness = ThemeData.estimateBrightnessForColor(
      Color(backgroundTheme.solidColor),
    );
    final Brightness brightness = requestedBrightness ?? defaultBrightness;

    // If a specific brightness is requested, we use color scheme generation from the primary color
    // to ensure text/backgrounds automatically adapt to light/dark properly.
    // If no specific brightness is requested, we use the exact hardcoded colors.

    if (requestedBrightness != null &&
        requestedBrightness != defaultBrightness) {
      // We need to invert or adapt to the requested brightness
      final seed = Color(senderBubble.backgroundColor);
      final scheme = ColorScheme.fromSeed(
        seedColor: seed,
        brightness: brightness,
      );

      return ThemeData(
        useMaterial3: true,
        brightness: brightness,
        colorScheme: scheme,
        appBarTheme: AppBarTheme(
          backgroundColor: scheme.surface,
          iconTheme: IconThemeData(
            color: scheme.onSurface,
            size: appAppearance.iconSize,
          ),
          titleTextStyle: safeGetFont(
            textTheme.fontFamily,
            color: scheme.onSurface,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        textTheme: TextTheme(
          bodyLarge: safeGetFont(
            textTheme.fontFamily,
            fontSize: textTheme.fontSize,
          ),
          bodyMedium: safeGetFont(
            textTheme.fontFamily,
            fontSize: textTheme.fontSize - 2,
          ),
        ),
        cardTheme: CardThemeData(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.only(
              topLeft: Radius.circular(senderBubble.radiusTopLeft),
              topRight: Radius.circular(senderBubble.radiusTopRight),
              bottomLeft: Radius.circular(senderBubble.radiusBottomLeft),
              bottomRight: Radius.circular(senderBubble.radiusBottomRight),
            ),
          ),
        ),
      );
    }

    // Default hardcoded colors for exact theme match
    return ThemeData(
      useMaterial3: true,
      brightness: defaultBrightness,
      scaffoldBackgroundColor: Color(backgroundTheme.solidColor),
      colorScheme: ColorScheme(
        brightness: defaultBrightness,
        primary: Color(senderBubble.backgroundColor),
        onPrimary: Color(textTheme.senderMessageColor),
        secondary: Color(appAppearance.sendButtonColor),
        onSecondary: Colors.white,
        secondaryContainer: Color(receiverBubble.backgroundColor),
        onSecondaryContainer: Color(textTheme.receiverMessageColor),
        surface: Color(appAppearance.appBarColor),
        onSurface: Color(appAppearance.appBarTitleColor),
        error: Colors.redAccent,
        onError: Colors.white,
      ),
      appBarTheme: AppBarTheme(
        backgroundColor: Color(appAppearance.appBarColor),
        iconTheme: IconThemeData(
          color: Color(appAppearance.appBarIconColor),
          size: appAppearance.iconSize,
        ),
        titleTextStyle: safeGetFont(
          textTheme.fontFamily,
          color: Color(appAppearance.appBarTitleColor),
          fontSize: 20,
          fontWeight: FontWeight.bold,
        ),
      ),
      textTheme: TextTheme(
        bodyLarge: safeGetFont(
          textTheme.fontFamily,
          fontSize: textTheme.fontSize,
        ),
        bodyMedium: safeGetFont(
          textTheme.fontFamily,
          fontSize: textTheme.fontSize - 2,
        ),
      ),
      cardTheme: CardThemeData(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(senderBubble.radiusTopLeft),
            topRight: Radius.circular(senderBubble.radiusTopRight),
            bottomLeft: Radius.circular(senderBubble.radiusBottomLeft),
            bottomRight: Radius.circular(senderBubble.radiusBottomRight),
          ),
        ),
      ),
    );
  }

  // ──────────────────────────────────────────────────────────────────────────
  // 1. WhatsApp
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetWhatsApp() => AdvancedThemeModel(
    id: 'whatsapp',
    name: 'WhatsApp',
    description: 'Classic WhatsApp messenger look with green accents',
    category: 'Professional',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFE7FFDB,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.1,
      opacity: 1.0,
      radiusTopLeft: 12,
      radiusTopRight: 0,
      radiusBottomLeft: 12,
      radiusBottomRight: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFFFFFFF,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.1,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 12,
      radiusBottomLeft: 12,
      radiusBottomRight: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFF000000,
      receiverMessageColor: 0xFF000000,
      timestampColor: 0xFF999999,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFEFE7DE,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF075E54,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFFFFFFFF,
      inputBackgroundColor: 0xFFFFFFFF,
      inputBorderColor: 0x00000000,
      inputBorderRadius: 24,
      inputTextColor: 0xFF000000,
      inputHintColor: 0xFF999999,
      sendButtonColor: 0xFF128C7E,
      sendButtonRadius: 24,
      iconColor: 0xFF888888,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 2. Telegram
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetTelegram() => AdvancedThemeModel(
    id: 'telegram',
    name: 'Telegram',
    description: 'Clean Telegram messenger style with blue accents',
    category: 'Professional',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFEEFFDE,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 16,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 0,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFFFFFFF,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 16,
      radiusTopRight: 16,
      radiusBottomLeft: 0,
      radiusBottomRight: 16,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFF000000,
      receiverMessageColor: 0xFF000000,
      timestampColor: 0xFF55AB5A,
      timestampSize: 12,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFC9D8E6,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF517DA2,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFFFFFFFF,
      inputBackgroundColor: 0xFFFFFFFF,
      inputBorderColor: 0x00000000,
      inputBorderRadius: 24,
      inputTextColor: 0xFF000000,
      inputHintColor: 0xFF999999,
      sendButtonColor: 0xFF517DA2,
      sendButtonRadius: 24,
      iconColor: 0xFF888888,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 3. iMessage
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetIMessage() => AdvancedThemeModel(
    id: 'imessage',
    name: 'iMessage',
    description: 'Apple iMessage style with blue sender bubbles',
    category: 'Professional',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF007AFF,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 18,
      radiusTopRight: 18,
      radiusBottomLeft: 18,
      radiusBottomRight: 4,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFE5E5EA,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 18,
      radiusTopRight: 18,
      radiusBottomLeft: 4,
      radiusBottomRight: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFFFFFFFF,
      receiverMessageColor: 0xFF000000,
      timestampColor: 0xFF8E8E93,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFFFFFFF,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFFF9F9F9,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF000000,
      appBarIconColor: 0xFF007AFF,
      inputBackgroundColor: 0xFFFFFFFF,
      inputBorderColor: 0xFFC7C7CC,
      inputBorderRadius: 20,
      inputTextColor: 0xFF000000,
      inputHintColor: 0xFF8E8E93,
      sendButtonColor: 0xFF007AFF,
      sendButtonRadius: 16,
      iconColor: 0xFF8E8E93,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 4. AMOLED Black
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetAmoledBlack() => AdvancedThemeModel(
    id: 'amoled',
    name: 'AMOLED Black',
    description: 'Pure black theme for AMOLED displays to save battery',
    category: 'AMOLED',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF333333,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 16,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 16,
      paddingHorizontal: 16,
      paddingVertical: 12,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF1A1A1A,
      gradientColors: [],
      borderColor: 0xFF333333,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 16,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 16,
      paddingHorizontal: 16,
      paddingVertical: 12,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFFFFFFFF,
      receiverMessageColor: 0xFFFFFFFF,
      timestampColor: 0xFF888888,
      timestampSize: 12,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF000000,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF000000,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFFFFFFFF,
      inputBackgroundColor: 0xFF1A1A1A,
      inputBorderColor: 0x00000000,
      inputBorderRadius: 24,
      inputTextColor: 0xFFFFFFFF,
      inputHintColor: 0xFF888888,
      sendButtonColor: 0xFFFFFFFF,
      sendButtonRadius: 24,
      iconColor: 0xFF888888,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 5. Discord
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetDiscord() => AdvancedThemeModel(
    id: 'discord',
    name: 'Discord',
    description: 'Discord-inspired dark theme with blurple accents',
    category: 'Professional',
    senderBubble: BubbleTheme(
      backgroundColor: 0x00000000,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 0,
      radiusBottomLeft: 0,
      radiusBottomRight: 0,
      paddingHorizontal: 0,
      paddingVertical: 4,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0x00000000,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 0,
      radiusBottomLeft: 0,
      radiusBottomRight: 0,
      paddingHorizontal: 0,
      paddingVertical: 4,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFFDCDDDE,
      receiverMessageColor: 0xFFDCDDDE,
      timestampColor: 0xFF72767D,
      timestampSize: 12,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF36393F,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF36393F,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFFB9BBBE,
      inputBackgroundColor: 0xFF40444B,
      inputBorderColor: 0x00000000,
      inputBorderRadius: 8,
      inputTextColor: 0xFFDCDDDE,
      inputHintColor: 0xFF72767D,
      sendButtonColor: 0xFF5865F2,
      sendButtonRadius: 8,
      iconColor: 0xFFB9BBBE,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 6. Material 3
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetMaterial3() => AdvancedThemeModel(
    id: 'material3',
    name: 'Material 3',
    description: 'Google Material You design language with dynamic colors',
    category: 'Modern',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFD3E3FD,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 24,
      radiusTopRight: 24,
      radiusBottomLeft: 24,
      radiusBottomRight: 8,
      paddingHorizontal: 16,
      paddingVertical: 12,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFF2F2F2,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 24,
      radiusTopRight: 24,
      radiusBottomLeft: 8,
      radiusBottomRight: 24,
      paddingHorizontal: 16,
      paddingVertical: 12,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFF041E49,
      receiverMessageColor: 0xFF1F1F1F,
      timestampColor: 0xFF444746,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFFFFFFF,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFFFFFFFF,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF1F1F1F,
      appBarIconColor: 0xFF444746,
      inputBackgroundColor: 0xFFF2F2F2,
      inputBorderColor: 0x00000000,
      inputBorderRadius: 28,
      inputTextColor: 0xFF1F1F1F,
      inputHintColor: 0xFF444746,
      sendButtonColor: 0xFF0B57D0,
      sendButtonRadius: 28,
      iconColor: 0xFF444746,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 7. Terminal
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetTerminal() => AdvancedThemeModel(
    id: 'terminal',
    name: 'Terminal',
    description: 'Classic terminal emulator with white text on black',
    category: 'Retro',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF1A1A1A,
      gradientColors: [],
      borderColor: 0xFFFFFFFF,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 0,
      radiusBottomLeft: 0,
      radiusBottomRight: 0,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF000000,
      gradientColors: [],
      borderColor: 0xFFFFFFFF,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 0,
      radiusBottomLeft: 0,
      radiusBottomRight: 0,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'monospace',
      fontSize: 14,
      fontWeight: 400,
      senderMessageColor: 0xFFFFFFFF,
      receiverMessageColor: 0xFFFFFFFF,
      timestampColor: 0xFFAAAAAA,
      timestampSize: 11,
      emojiSize: 22,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF000000,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF000000,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFFFFFFFF,
      inputBackgroundColor: 0xFF000000,
      inputBorderColor: 0xFFFFFFFF,
      inputBorderRadius: 0,
      inputTextColor: 0xFFFFFFFF,
      inputHintColor: 0xFFAAAAAA,
      sendButtonColor: 0xFFFFFFFF,
      sendButtonRadius: 0,
      iconColor: 0xFFFFFFFF,
      iconSize: 22,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 8. Matrix
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetMatrix() => AdvancedThemeModel(
    id: 'matrix',
    name: 'Matrix',
    description: 'The Matrix digital rain aesthetic with green code',
    category: 'Cyber',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF003300,
      gradientColors: [],
      borderColor: 0xFF00FF41,
      borderWidth: 1,
      shadowOpacity: 0.15,
      opacity: 1.0,
      radiusTopLeft: 6,
      radiusTopRight: 6,
      radiusBottomLeft: 6,
      radiusBottomRight: 2,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF0A0A0A,
      gradientColors: [],
      borderColor: 0xFF00FF41,
      borderWidth: 1,
      shadowOpacity: 0.15,
      opacity: 1.0,
      radiusTopLeft: 2,
      radiusTopRight: 6,
      radiusBottomLeft: 6,
      radiusBottomRight: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Source Code Pro',
      fontSize: 14,
      fontWeight: 400,
      senderMessageColor: 0xFF00FF41,
      receiverMessageColor: 0xFF00FF41,
      timestampColor: 0xFF008F11,
      timestampSize: 11,
      emojiSize: 22,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF000000,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF001A00,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF00FF41,
      appBarIconColor: 0xFF00FF41,
      inputBackgroundColor: 0xFF0A0A0A,
      inputBorderColor: 0xFF00FF41,
      inputBorderRadius: 4,
      inputTextColor: 0xFF00FF41,
      inputHintColor: 0xFF006600,
      sendButtonColor: 0xFF00FF41,
      sendButtonRadius: 4,
      iconColor: 0xFF00FF41,
      iconSize: 22,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 9. Cyberpunk
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetCyberpunk() => AdvancedThemeModel(
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'Neon-soaked cyberpunk aesthetic with pink and cyan',
    category: 'Cyber',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFFF2A6D,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.3,
      opacity: 1.0,
      radiusTopLeft: 14,
      radiusTopRight: 14,
      radiusBottomLeft: 14,
      radiusBottomRight: 4,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF1A1A2E,
      gradientColors: [],
      borderColor: 0xFF05D9E8,
      borderWidth: 1,
      shadowOpacity: 0.3,
      opacity: 1.0,
      radiusTopLeft: 4,
      radiusTopRight: 14,
      radiusBottomLeft: 14,
      radiusBottomRight: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 700,
      senderMessageColor: 0xFFFFFFFF,
      receiverMessageColor: 0xFF05D9E8,
      timestampColor: 0xFFFF2A6D,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF0D0221,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF0D0221,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF05D9E8,
      appBarIconColor: 0xFFFF2A6D,
      inputBackgroundColor: 0xFF1A1A2E,
      inputBorderColor: 0xFF05D9E8,
      inputBorderRadius: 8,
      inputTextColor: 0xFFFFFFFF,
      inputHintColor: 0xFF555577,
      sendButtonColor: 0xFFFF2A6D,
      sendButtonRadius: 8,
      iconColor: 0xFF05D9E8,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 10. Old Phone
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetOldPhone() => AdvancedThemeModel(
    id: 'oldphone',
    name: 'Old Phone',
    description: 'Classic keypad phone aesthetics',
    category: 'Retro',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFB8C4A8,
      gradientColors: [],
      borderColor: 0xFF3B4A3F,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 2,
      radiusTopRight: 2,
      radiusBottomLeft: 2,
      radiusBottomRight: 0,
      paddingHorizontal: 10,
      paddingVertical: 6,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFD0D8C0,
      gradientColors: [],
      borderColor: 0xFF3B4A3F,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 2,
      radiusBottomLeft: 2,
      radiusBottomRight: 2,
      paddingHorizontal: 10,
      paddingVertical: 6,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Courier New',
      fontSize: 14,
      fontWeight: 400,
      senderMessageColor: 0xFF3B4A3F,
      receiverMessageColor: 0xFF3B4A3F,
      timestampColor: 0xFF5A6A5F,
      timestampSize: 10,
      emojiSize: 20,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFC7D0BE,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF5A6A5F,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFC7D0BE,
      appBarIconColor: 0xFFC7D0BE,
      inputBackgroundColor: 0xFFD0D8C0,
      inputBorderColor: 0xFF3B4A3F,
      inputBorderRadius: 2,
      inputTextColor: 0xFF3B4A3F,
      inputHintColor: 0xFF5A6A5F,
      sendButtonColor: 0xFF3B4A3F,
      sendButtonRadius: 2,
      iconColor: 0xFF3B4A3F,
      iconSize: 22,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 11. LCD Display
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetLCD() => AdvancedThemeModel(
    id: 'lcd',
    name: 'LCD Display',
    description: 'Green LCD calculator display aesthetic',
    category: 'Retro',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF8EAC5F,
      gradientColors: [],
      borderColor: 0xFF2D3B1A,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 2,
      radiusTopRight: 2,
      radiusBottomLeft: 2,
      radiusBottomRight: 0,
      paddingHorizontal: 10,
      paddingVertical: 6,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFA8CC7D,
      gradientColors: [],
      borderColor: 0xFF2D3B1A,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 2,
      radiusBottomLeft: 2,
      radiusBottomRight: 2,
      paddingHorizontal: 10,
      paddingVertical: 6,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Courier New',
      fontSize: 14,
      fontWeight: 400,
      senderMessageColor: 0xFF2D3B1A,
      receiverMessageColor: 0xFF2D3B1A,
      timestampColor: 0xFF4A5A30,
      timestampSize: 10,
      emojiSize: 20,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF9EBC6D,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF6A8A3C,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF2D3B1A,
      appBarIconColor: 0xFF2D3B1A,
      inputBackgroundColor: 0xFFA8CC7D,
      inputBorderColor: 0xFF2D3B1A,
      inputBorderRadius: 2,
      inputTextColor: 0xFF2D3B1A,
      inputHintColor: 0xFF4A5A30,
      sendButtonColor: 0xFF2D3B1A,
      sendButtonRadius: 2,
      iconColor: 0xFF2D3B1A,
      iconSize: 22,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 12. CRT Monitor
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetCRT() => AdvancedThemeModel(
    id: 'crt',
    name: 'CRT Monitor',
    description: 'Phosphor green CRT monitor with soft glow effect',
    category: 'Retro',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF0D2B0D,
      gradientColors: [],
      borderColor: 0xFF33FF33,
      borderWidth: 0.5,
      shadowOpacity: 0.3,
      opacity: 1.0,
      radiusTopLeft: 6,
      radiusTopRight: 6,
      radiusBottomLeft: 6,
      radiusBottomRight: 2,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF061506,
      gradientColors: [],
      borderColor: 0xFF33FF33,
      borderWidth: 0.5,
      shadowOpacity: 0.3,
      opacity: 1.0,
      radiusTopLeft: 2,
      radiusTopRight: 6,
      radiusBottomLeft: 6,
      radiusBottomRight: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Source Code Pro',
      fontSize: 14,
      fontWeight: 400,
      senderMessageColor: 0xFF33FF33,
      receiverMessageColor: 0xFF33FF33,
      timestampColor: 0xFF1AAA1A,
      timestampSize: 11,
      emojiSize: 22,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF0A1A0A,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF0A1A0A,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF33FF33,
      appBarIconColor: 0xFF33FF33,
      inputBackgroundColor: 0xFF0D2B0D,
      inputBorderColor: 0xFF33FF33,
      inputBorderRadius: 4,
      inputTextColor: 0xFF33FF33,
      inputHintColor: 0xFF117711,
      sendButtonColor: 0xFF33FF33,
      sendButtonRadius: 4,
      iconColor: 0xFF33FF33,
      iconSize: 22,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 13. Windows 95
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetWin95() => AdvancedThemeModel(
    id: 'win95',
    name: 'Windows 95',
    description: 'Classic Windows 95 UI with teal taskbar and raised buttons',
    category: 'Retro',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFFFFFFF,
      gradientColors: [],
      borderColor: 0xFF808080,
      borderWidth: 2,
      shadowOpacity: 0.1,
      opacity: 1.0,
      radiusTopLeft: 2,
      radiusTopRight: 2,
      radiusBottomLeft: 2,
      radiusBottomRight: 0,
      paddingHorizontal: 10,
      paddingVertical: 6,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFFFFFFF,
      gradientColors: [],
      borderColor: 0xFF808080,
      borderWidth: 2,
      shadowOpacity: 0.1,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 2,
      radiusBottomLeft: 2,
      radiusBottomRight: 2,
      paddingHorizontal: 10,
      paddingVertical: 6,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Courier New',
      fontSize: 14,
      fontWeight: 400,
      senderMessageColor: 0xFF000000,
      receiverMessageColor: 0xFF000000,
      timestampColor: 0xFF808080,
      timestampSize: 10,
      emojiSize: 20,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFC0C0C0,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF008080,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFFFFFFFF,
      inputBackgroundColor: 0xFFFFFFFF,
      inputBorderColor: 0xFF808080,
      inputBorderRadius: 0,
      inputTextColor: 0xFF000000,
      inputHintColor: 0xFF808080,
      sendButtonColor: 0xFF008080,
      sendButtonRadius: 0,
      iconColor: 0xFF000000,
      iconSize: 22,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 14. Game Boy
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetGameBoy() => AdvancedThemeModel(
    id: 'gameboy',
    name: 'Game Boy',
    description: 'Nintendo Game Boy 4-shade olive green palette',
    category: 'Gaming',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF8BAC0F,
      gradientColors: [],
      borderColor: 0xFF306230,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 4,
      radiusTopRight: 4,
      radiusBottomLeft: 4,
      radiusBottomRight: 0,
      paddingHorizontal: 10,
      paddingVertical: 6,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF306230,
      gradientColors: [],
      borderColor: 0xFF0F380F,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 4,
      radiusBottomLeft: 4,
      radiusBottomRight: 4,
      paddingHorizontal: 10,
      paddingVertical: 6,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Courier New',
      fontSize: 14,
      fontWeight: 700,
      senderMessageColor: 0xFF0F380F,
      receiverMessageColor: 0xFF9BBC0F,
      timestampColor: 0xFF306230,
      timestampSize: 10,
      emojiSize: 20,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF9BBC0F,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF0F380F,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF9BBC0F,
      appBarIconColor: 0xFF9BBC0F,
      inputBackgroundColor: 0xFF8BAC0F,
      inputBorderColor: 0xFF0F380F,
      inputBorderRadius: 4,
      inputTextColor: 0xFF0F380F,
      inputHintColor: 0xFF306230,
      sendButtonColor: 0xFF306230,
      sendButtonRadius: 4,
      iconColor: 0xFF9BBC0F,
      iconSize: 22,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 15. Dot Matrix
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetDotMatrix() => AdvancedThemeModel(
    id: 'dotmatrix',
    name: 'Dot Matrix',
    description: 'Dot matrix printer paper aesthetic with monospace text',
    category: 'Retro',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFEDE8D6,
      gradientColors: [],
      borderColor: 0xFFCCC5AE,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 2,
      radiusTopRight: 2,
      radiusBottomLeft: 2,
      radiusBottomRight: 0,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFE5E0CE,
      gradientColors: [],
      borderColor: 0xFFCCC5AE,
      borderWidth: 1,
      shadowOpacity: 0,
      opacity: 1.0,
      radiusTopLeft: 0,
      radiusTopRight: 2,
      radiusBottomLeft: 2,
      radiusBottomRight: 2,
      paddingHorizontal: 12,
      paddingVertical: 8,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Source Code Pro',
      fontSize: 14,
      fontWeight: 400,
      senderMessageColor: 0xFF333333,
      receiverMessageColor: 0xFF333333,
      timestampColor: 0xFF888888,
      timestampSize: 10,
      emojiSize: 20,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFF5F0E1,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFFD5D0C1,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF333333,
      appBarIconColor: 0xFF333333,
      inputBackgroundColor: 0xFFEDE8D6,
      inputBorderColor: 0xFFCCC5AE,
      inputBorderRadius: 2,
      inputTextColor: 0xFF333333,
      inputHintColor: 0xFF888888,
      sendButtonColor: 0xFF333333,
      sendButtonRadius: 2,
      iconColor: 0xFF333333,
      iconSize: 22,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 16. Glassmorphism
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetGlass() => AdvancedThemeModel(
    id: 'glass',
    name: 'Glassmorphism',
    description: 'Frosted glass effect with translucent surfaces and blur',
    category: 'Modern',
    senderBubble: BubbleTheme(
      backgroundColor: 0x80FFFFFF,
      gradientColors: [],
      borderColor: 0x40FFFFFF,
      borderWidth: 1,
      shadowOpacity: 0.15,
      opacity: 0.5,
      radiusTopLeft: 20,
      radiusTopRight: 20,
      radiusBottomLeft: 20,
      radiusBottomRight: 6,
      paddingHorizontal: 16,
      paddingVertical: 12,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0x40FFFFFF,
      gradientColors: [],
      borderColor: 0x30FFFFFF,
      borderWidth: 1,
      shadowOpacity: 0.1,
      opacity: 0.25,
      radiusTopLeft: 6,
      radiusTopRight: 20,
      radiusBottomLeft: 20,
      radiusBottomRight: 20,
      paddingHorizontal: 16,
      paddingVertical: 12,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFF1A1A2E,
      receiverMessageColor: 0xFF1A1A2E,
      timestampColor: 0xFF666688,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFE8E0F0,
      gradientColors: [0xFFE8E0F0, 0xFFC8D0F0, 0xFFD0E8E8],
      wallpaperUrl: null,
      blur: 20,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0x80FFFFFF,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF1A1A2E,
      appBarIconColor: 0xFF1A1A2E,
      inputBackgroundColor: 0x60FFFFFF,
      inputBorderColor: 0x40FFFFFF,
      inputBorderRadius: 24,
      inputTextColor: 0xFF1A1A2E,
      inputHintColor: 0xFF8888AA,
      sendButtonColor: 0xFF6366F1,
      sendButtonRadius: 24,
      iconColor: 0xFF6366F1,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 17. Neumorphism
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetNeumorphism() => AdvancedThemeModel(
    id: 'neumorphism',
    name: 'Neumorphism',
    description: 'Soft UI with extruded elements and subtle shadow play',
    category: 'Modern',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFE0E5EC,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.3,
      opacity: 1.0,
      radiusTopLeft: 20,
      radiusTopRight: 20,
      radiusBottomLeft: 20,
      radiusBottomRight: 6,
      paddingHorizontal: 16,
      paddingVertical: 12,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFE0E5EC,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.3,
      opacity: 1.0,
      radiusTopLeft: 6,
      radiusTopRight: 20,
      radiusBottomLeft: 20,
      radiusBottomRight: 20,
      paddingHorizontal: 16,
      paddingVertical: 12,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: 500,
      senderMessageColor: 0xFF2D3436,
      receiverMessageColor: 0xFF2D3436,
      timestampColor: 0xFF636E72,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFE0E5EC,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFFE0E5EC,
      appBarGradientColors: [],
      appBarTitleColor: 0xFF2D3436,
      appBarIconColor: 0xFF2D3436,
      inputBackgroundColor: 0xFFE0E5EC,
      inputBorderColor: 0x00000000,
      inputBorderRadius: 20,
      inputTextColor: 0xFF2D3436,
      inputHintColor: 0xFFA0A8B0,
      sendButtonColor: 0xFF6C5CE7,
      sendButtonRadius: 20,
      iconColor: 0xFF636E72,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 18. Sunset
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetSunset() => AdvancedThemeModel(
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm sunset palette with vibrant orange and pink tones',
    category: 'Modern',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFFF6B35,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.15,
      opacity: 1.0,
      radiusTopLeft: 18,
      radiusTopRight: 18,
      radiusBottomLeft: 18,
      radiusBottomRight: 4,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFF7418F,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.15,
      opacity: 1.0,
      radiusTopLeft: 4,
      radiusTopRight: 18,
      radiusBottomLeft: 18,
      radiusBottomRight: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFFFFFFFF,
      receiverMessageColor: 0xFFFFFFFF,
      timestampColor: 0xFFCC8844,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFFFF3E0,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFFFF6B35,
      appBarGradientColors: [0xFFFF6B35, 0xFFF7418F],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFFFFFFFF,
      inputBackgroundColor: 0xFFFFFFFF,
      inputBorderColor: 0xFFFFCCBC,
      inputBorderRadius: 24,
      inputTextColor: 0xFF3E2723,
      inputHintColor: 0xFFBCAAA4,
      sendButtonColor: 0xFFFF6B35,
      sendButtonRadius: 24,
      iconColor: 0xFFF7418F,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 19. Ocean
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetOcean() => AdvancedThemeModel(
    id: 'ocean',
    name: 'Ocean',
    description: 'Deep ocean blues with aqua highlights and white text',
    category: 'Modern',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF00BCD4,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.2,
      opacity: 1.0,
      radiusTopLeft: 16,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 4,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF0288D1,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.2,
      opacity: 1.0,
      radiusTopLeft: 4,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 16,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFFFFFFFF,
      receiverMessageColor: 0xFFFFFFFF,
      timestampColor: 0xFF80DEEA,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF1A237E,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF0D47A1,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFF80DEEA,
      inputBackgroundColor: 0xFF1A237E,
      inputBorderColor: 0xFF0288D1,
      inputBorderRadius: 24,
      inputTextColor: 0xFFFFFFFF,
      inputHintColor: 0xFF5C6BC0,
      sendButtonColor: 0xFF00BCD4,
      sendButtonRadius: 24,
      iconColor: 0xFF80DEEA,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 20. Forest
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetForest() => AdvancedThemeModel(
    id: 'forest',
    name: 'Forest',
    description: 'Deep forest greens with earthy brown accents',
    category: 'Modern',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF4CAF50,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.2,
      opacity: 1.0,
      radiusTopLeft: 16,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 4,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF795548,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.2,
      opacity: 1.0,
      radiusTopLeft: 4,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 16,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFFF5F5F0,
      receiverMessageColor: 0xFFF5F5F0,
      timestampColor: 0xFFA5D6A7,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF1B5E20,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF2E7D32,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFF5F5F0,
      appBarIconColor: 0xFFA5D6A7,
      inputBackgroundColor: 0xFF1B5E20,
      inputBorderColor: 0xFF4CAF50,
      inputBorderRadius: 24,
      inputTextColor: 0xFFF5F5F0,
      inputHintColor: 0xFF66BB6A,
      sendButtonColor: 0xFF4CAF50,
      sendButtonRadius: 24,
      iconColor: 0xFFA5D6A7,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 21. Lavender
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetLavender() => AdvancedThemeModel(
    id: 'lavender',
    name: 'Lavender',
    description: 'Soft lavender and purple palette with pastel pink accents',
    category: 'Modern',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFF7C4DFF,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.15,
      opacity: 1.0,
      radiusTopLeft: 18,
      radiusTopRight: 18,
      radiusBottomLeft: 18,
      radiusBottomRight: 4,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFFF3E5F5,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.1,
      opacity: 1.0,
      radiusTopLeft: 4,
      radiusTopRight: 18,
      radiusBottomLeft: 18,
      radiusBottomRight: 18,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFFFFFFFF,
      receiverMessageColor: 0xFF311B92,
      timestampColor: 0xFF9575CD,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFFE8DEF8,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF6200EA,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFFFFFFF,
      appBarIconColor: 0xFFE8DEF8,
      inputBackgroundColor: 0xFFF3E5F5,
      inputBorderColor: 0xFFCE93D8,
      inputBorderRadius: 24,
      inputTextColor: 0xFF311B92,
      inputHintColor: 0xFF9575CD,
      sendButtonColor: 0xFF7C4DFF,
      sendButtonRadius: 24,
      iconColor: 0xFF9575CD,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // 22. Dracula
  // ──────────────────────────────────────────────────────────────────────────
  factory AdvancedThemeModel.presetDracula() => AdvancedThemeModel(
    id: 'dracula',
    name: 'Dracula',
    description: 'Dracula color scheme with dark purples and pastel accents',
    category: 'Cyber',
    senderBubble: BubbleTheme(
      backgroundColor: 0xFFBD93F9,
      gradientColors: [],
      borderColor: 0x00000000,
      borderWidth: 0,
      shadowOpacity: 0.15,
      opacity: 1.0,
      radiusTopLeft: 16,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 4,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    receiverBubble: BubbleTheme(
      backgroundColor: 0xFF44475A,
      gradientColors: [],
      borderColor: 0xFF6272A4,
      borderWidth: 1,
      shadowOpacity: 0.1,
      opacity: 1.0,
      radiusTopLeft: 4,
      radiusTopRight: 16,
      radiusBottomLeft: 16,
      radiusBottomRight: 16,
      paddingHorizontal: 14,
      paddingVertical: 10,
    ),
    textTheme: ChatTextTheme(
      fontFamily: 'Roboto',
      fontSize: 16,
      fontWeight: 400,
      senderMessageColor: 0xFF282A36,
      receiverMessageColor: 0xFFF8F8F2,
      timestampColor: 0xFF6272A4,
      timestampSize: 11,
      emojiSize: 24,
    ),
    backgroundTheme: ChatBackgroundTheme(
      solidColor: 0xFF282A36,
      gradientColors: [],
      wallpaperUrl: null,
      blur: 0,
      brightness: 1.0,
      opacity: 1.0,
    ),
    appAppearance: AppAppearanceTheme(
      appBarColor: 0xFF282A36,
      appBarGradientColors: [],
      appBarTitleColor: 0xFFF8F8F2,
      appBarIconColor: 0xFFFF79C6,
      inputBackgroundColor: 0xFF44475A,
      inputBorderColor: 0xFF6272A4,
      inputBorderRadius: 12,
      inputTextColor: 0xFFF8F8F2,
      inputHintColor: 0xFF6272A4,
      sendButtonColor: 0xFFBD93F9,
      sendButtonRadius: 12,
      iconColor: 0xFFFF79C6,
      iconSize: 24,
    ),
  );

  // ──────────────────────────────────────────────────────────────────────────
  // All Presets
  // ──────────────────────────────────────────────────────────────────────────
  static List<AdvancedThemeModel> get presets => [
    AdvancedThemeModel.presetWhatsApp(),
    AdvancedThemeModel.presetTelegram(),
    AdvancedThemeModel.presetIMessage(),
    AdvancedThemeModel.presetAmoledBlack(),
    AdvancedThemeModel.presetDiscord(),
    AdvancedThemeModel.presetMaterial3(),
    AdvancedThemeModel.presetTerminal(),
    AdvancedThemeModel.presetMatrix(),
    AdvancedThemeModel.presetCyberpunk(),
    AdvancedThemeModel.presetOldPhone(),
    AdvancedThemeModel.presetLCD(),
    AdvancedThemeModel.presetCRT(),
    AdvancedThemeModel.presetWin95(),
    AdvancedThemeModel.presetGameBoy(),
    AdvancedThemeModel.presetDotMatrix(),
    AdvancedThemeModel.presetGlass(),
    AdvancedThemeModel.presetNeumorphism(),
    AdvancedThemeModel.presetSunset(),
    AdvancedThemeModel.presetOcean(),
    AdvancedThemeModel.presetForest(),
    AdvancedThemeModel.presetLavender(),
    AdvancedThemeModel.presetDracula(),
  ];
}

@freezed
abstract class BubbleTheme with _$BubbleTheme {
  const BubbleTheme._();
  const factory BubbleTheme({
    required int backgroundColor,
    required List<int> gradientColors,
    required int borderColor,
    required double borderWidth,
    required double shadowOpacity,
    required double opacity,
    required double radiusTopLeft,
    required double radiusTopRight,
    required double radiusBottomLeft,
    required double radiusBottomRight,
    required double paddingHorizontal,
    required double paddingVertical,
  }) = _BubbleTheme;

  factory BubbleTheme.fromJson(Map<String, dynamic> json) =>
      _$BubbleThemeFromJson(json);
}

@freezed
abstract class ChatTextTheme with _$ChatTextTheme {
  const ChatTextTheme._();
  const factory ChatTextTheme({
    required String fontFamily,
    required double fontSize,
    required int fontWeight,
    required int senderMessageColor,
    required int receiverMessageColor,
    required int timestampColor,
    required double timestampSize,
    required double emojiSize,
  }) = _ChatTextTheme;

  factory ChatTextTheme.fromJson(Map<String, dynamic> json) =>
      _$ChatTextThemeFromJson(json);
}

@freezed
abstract class ChatBackgroundTheme with _$ChatBackgroundTheme {
  const ChatBackgroundTheme._();
  const factory ChatBackgroundTheme({
    required int solidColor,
    required List<int> gradientColors,
    required String? wallpaperUrl,
    required double blur,
    required double brightness,
    required double opacity,
  }) = _ChatBackgroundTheme;

  factory ChatBackgroundTheme.fromJson(Map<String, dynamic> json) =>
      _$ChatBackgroundThemeFromJson(json);
}

@freezed
abstract class AppAppearanceTheme with _$AppAppearanceTheme {
  const AppAppearanceTheme._();
  const factory AppAppearanceTheme({
    required int appBarColor,
    required List<int> appBarGradientColors,
    required int appBarTitleColor,
    required int appBarIconColor,

    required int inputBackgroundColor,
    required int inputBorderColor,
    required double inputBorderRadius,
    required int inputTextColor,
    required int inputHintColor,

    required int sendButtonColor,
    required double sendButtonRadius,

    required int iconColor,
    required double iconSize,
  }) = _AppAppearanceTheme;

  factory AppAppearanceTheme.fromJson(Map<String, dynamic> json) =>
      _$AppAppearanceThemeFromJson(json);
}
